name: Trigger deploys (on liteyuki)

on:
  push:
    branches:
      - main

# permissions:
#   contents: write
#   statuses: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Gitea workflow via API
        run: |
          curl -X POST \
            "https://git.liteyuki.org/${{ secrets.GITEA_URI }}" \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{
              "event": "github-push",
              "ref": "refs/heads/main",
              "inputs": {
                "github_repo": "${{ github.repository }}",
                "github_sha": "${{ github.sha }}",
                "github_ref": "${{ github.ref }}"
              }
            }'